import random;
import os
import time

quotes = [
"Just changed my Facebook name to, No one, so when I see stupid posts I can click like and it will say No one likes this.",
"What do you call a bear with no teeth? A gummy bear!",
"I once farted in an elevator it was wrong on so many levels.",
"I wondered why the frisbee was getting bigger, and then it hit me.",
"I used to like my neighbors, until they put a password on their Wi-Fi.",
"What is the difference between a smart man and a stupid man? Nothing. They both think they know everything.",
"Light travels faster than sound. This is why some people appear bright until they speak.",
"What is the difference between men and pigs? Pigs dont turn into men when they drink.",
"A doctor tells a woman she can no longer touch anything alcoholic. So she gets a divorce.",
"Alcohol is a perfect solvent- It dissolves marriages, families and careers.",
"Temples are free to enter but still empty. Pubs charge to enter, but are full. People ignore inner peace and choose to pay for self destruction",
"Maybe if we start telling people the brain is an app they will start using it.",
"Entered what I ate today into my new fitness app and it just sent an ambulance to my house.",
"I think my neighbor is stalking me as she has been googling my name on her computer. I saw it through my telescope last night.",
"I changed my password to incorrect. So whenever I forget what it is the,computer will say - Your password is incorrect.",
"A computer once beat me at chess, but it was no match for me at kick boxing.",
"A clean house is the sign of a broken computer.",
"My email password has been hacked. That's the third time I have had to rename the cat.",
"Q: What do you call the security outside of a Samsung Store? A: Guardians of the Galaxy.",
"A TV can insult your intelligence, but nothing rubs it in like a computer.",
"It is ok computer, I go to sleep after 20 minutes of inactivity too.",
"I tried to escape the Apple store. I was not able to do because there were no Windows.",
"I want to die peacefully in my sleep, like my grandfather.. Not screaming and yelling like the passengers in his car.",
"We live in a society where pizza gets to your house before the police.",
"Knowledge is knowing a tomato is a fruit; Wisdom is not putting it in a fruit salad.",
"Politicians and diapers have one thing in common. They should both be changed regularly, and for the same reason.",
"If God is watching us, the least we can do is be entertaining.",
"I asked God for a bike, but I know God does not work that way. So I stole a bike and asked for forgiveness.",
"To steal ideas from one person is plagiarism. To steal from many is research.",
"I thought I wanted a career, turns out I just wanted paychecks.",
"Knowledge is knowing a tomato is a fruit, Wisdom is not putting it in a fruit salad.",
"Politicians and diapers have one thing in common. They should both be changed regularly, and for the same reason.",
"The early bird might get the worm, but the second mouse gets the cheese.",
"Evening news is where they begin with  Good evening, and then proceed to tell you why it isn't.",
"I'm reading a book about anti-gravity. It's impossible to put down!",
"Did you hear about the mathematician who's afraid of negative numbers? He'll stop at nothing to avoid them.",
"My wife told me to stop singing Wonderwall. I said maybe...",
"I haven't slept for ten days, because that would be too long.",
"I used to hate facial hair, but then it grew on me.",
"Dad, can you put my shoes on? No, I don't think they'll fit me.",
"Can February March? No, but April May!",
"It's inappropriate to make a dad joke if you're not a dad. It's a faux pa.",
"How do you organize a space party? You planet!",
"I only know 25 letters of the alphabet. I don't know y.",
"What's the best thing about Switzerland? I don't know, but the flag is a big plus.",
"I invented a new word: Plagiarism!",
"Did you get a haircut? No, I got them all cut!",
"I stayed up all night wondering where the sun went. Then it dawned on me.",
"This graveyard looks overcrowded. People are dying to get in!",
"I decided to sell my vacuum cleaner. It was just gathering dust!",
"I'm so good at sleeping. I can do it with my eyes closed!",
"Want to hear a joke about construction? I'm still working on it!",
"My dad was stealing from his job as a road worker. I didn't believe it at first. But when I got home, all the signs were there.",
"How do you make a Kleenex dance? Put a little boogie in it!",
"I'm afraid for the calendar. Its days are numbered.",
"My wife is really mad at the fact that I have no sense of direction. So I packed up my stuff and right!",
"How do you make 7 even? Take away the s!",
"What do you call someone with no body and no nose? Nobody knows!",
"I made a pencil with two erasers. It was pointless.",
"How did Harry Potter get down the hill? Walking. JK! Rowling.",
"I lost my job at the bank. A woman asked me to check her balance, so I pushed her over.",
"Why should you never trust stairs? They're always up to something!",
"I hate jokes about German sausage. They're the wurst.",
"Did you know the first French fries weren't actually cooked in France? They were cooked in Greece.",
"I'm terrified of elevators. I'll take steps to avoid them.",
"Why don't scientists trust atoms? Because they make up everything!",
"To whoever stole my copy of Microsoft Office: I will find you. You have my Word!",
"What's the difference between a poorly dressed man on a tricycle and a well-dressed man on a bicycle? Attire!",
"How do you follow Will Smith in the snow? You follow the fresh prints!",
"If April showers bring May flowers, what do May flowers bring? Pilgrims!",
"I thought the dryer was shrinking my clothes. Turns out it was the refrigerator all along.",
"What do you call a factory that makes okay products? A satisfactory!",
"Dear Math, grow up and solve your own problems.",
"What did the janitor say when he jumped out of the closet? Supplies!",
"Have you heard about the chocolate record player? It sounds pretty sweet.",
"What did the ocean say to the beach? Nothing, it just waved.",
"Why do seagulls fly over the ocean? Because if they flew over the bay, we'd call them bagels.",
"I only know 25 letters of the alphabet. I don't know y.",
"How does the solar system hold up its pants? With an asteroid belt!",
"What did one wall say to the other wall? I'll meet you at the corner!",
"What do you call a nosy pepper? Jalapeño business!",
"Why don't eggs tell jokes? They'd crack each other up.",
"What's orange and sounds like a parrot? A carrot!",
"Why did the coffee file a police report? It got mugged.",
"What's the best time to go to the dentist? Tooth hurt-y!",
"How do you organize a space party? You planet.",
"Why don't scientists trust atoms? Because they make up everything.",
"What do clouds wear under their raincoats? Thunderwear!",
"What do you call a dinosaur that crashes his car? Tyrannosaurus Wrecks.",
"Why did the scarecrow win an award? Because he was outstanding in his field.",
"How does a penguin build its house? Igloos it together!",
"Why don't skeletons fight each other? They don't have the guts.",
"What do you call a fish wearing a bowtie? Sofishticated!",
"How do you make a tissue dance? You put a little boogie in it.",
"Why did the math book look so sad? Because of all of its problems!",
"What do you call a sleeping bull? A bulldozer!",
"Did you hear the rumor about butter? Well, I'm not going to spread it!",
"Why can't a bicycle stand up by itself? It's two tired.",
"What do you call a belt made of watches? A waist of time!",
"How do you make holy water? You boil the hell out of it.",
"I wouldn't buy anything with velcro. It's a total rip-off.",
"Why did the golfer wear two pairs of pants? In case he got a hole in one!",
"What do you call a fake noodle? An impasta.",
"How many apples grow on a tree? All of them!",
"What's the best thing about Switzerland? I don't know, but the flag is a big plus.",
"What do you call a dog that can do magic? A labracadabrador.",
"Why do chicken coops only have two doors? Because if they had four, they would be chicken sedans!",
"What do you call a bear with no teeth? A gummy bear!",
"Why did the cookie go to the doctor? Because it felt crumbly.",
"How do you catch a tame rabbit? Tame way, unique up on it!",
"What do you call a cow with no legs? Ground beef!",
"Why don't oysters donate? Because they are shellfish.",
"What do you call a pig that does karate? A pork chop!",
"Why did the bicycle fall over? Because it was two-tired!",
"What do you call a fish that needs help with his or her vocals? Auto-Tuna.",
"Why don't elephants use computers? They're afraid of the mouse!",
"What do you call a moose with no name? Anonymoose!",
"Why did the tomato turn red? Because it saw the salad dressing!",
"What do you call a sleeping bull? A bulldozer.",
"Did you hear about the kidnapping at school? It's fine, he woke up.",
"A furniture store keeps calling me. All I wanted was one night stand.",
"What do you call a bear in the rain? A drizzly bear.",
"Why did the stadium get hot after the game? All of the fans left.",
"What do you call a dinosaur that loves to sleep? A dino-snore!",
"Where do fruits go on vacation? Pear-is!",
"What do you call a fish that wears a crown? A king fish.",
"Why don't mountains ever get cold? They wear snow caps.",
"What's a skeleton's least favorite room in the house? The living room.",
"Why did the banana go to the doctor? It wasn't peeling well.",
"How do you make a lemon drop? Just let it fall.",
"What do you call a duck that gets all A's? A wise quacker.",
"Why don't eggs tell jokes? They'd crack each other up.",
"What's a tornado's favorite game to play? Twister!",
"What do you call a grizzly bear caught in the rain? A drizzly bear.",
"Why don't teddy bears ever order dessert? They're always stuffed.",
"What do you call a dinosaur fart? A blast from the past!",
"How do you organize a space party? You planet.",
"Why did the picture go to jail? Because it was framed.",
"What do you call a fake stone in Ireland? A sham rock.",
"Why don't scientists trust atoms? Because they make up everything.",
"I'm reading a book on the history of glue. I just can't seem to put it down.",
"Why did the coffee file a police report? It got mugged.",
"What did the grape say when it got stepped on? Nothing, it just let out a little wine!"
]

runCommand = True

def clearConsole():
    clear = lambda: os.system("clear")
    clear()

while runCommand == True:
    clearConsole()
    selectedQuote = random.choice(quotes)
    try:
        os.system("cowsay '{0}'".format(selectedQuote.replace("'", "'\"'\"'")))
        time.sleep(10) # sleep for some time.
    except Exception as err:
        runCommand = False
        print(selectedQuote)
        
        
